Add the authPlugins types to ConnectionOptions
My builds started failing today with error TS2339: Property 'authPlugins' does not exist on type 'ConnectionOptions'.